spring.application.name=OAuth2Login

spring.security.oauth2.client.registration.google.client-id= 420832916982-v32d948vlijonc83cnv68bb3uedtchsv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/contacts

# Thymeleaf configuration
spring.thymeleaf.cache=false

# Server configuration
server.error.include-stacktrace=never